services:
  postgres:
    image: postgres:15
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - ./tests/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
